In [1]:
import pandas as pd    ##data handling
import numpy          ##numerical python  in mathematical calc and array handling

In [5]:
data = pd.read_csv('data_arrhythmia.csv')
b=10

In [7]:
print(type(data))
type(b)

<class 'pandas.core.frame.DataFrame'>


int

In [3]:
data.head(10)

Age  Sex  Height  Weight  qrs_duration  p-r_interval  q-t_interval  \
0   75    0     190      80            91           193           371   
1   56    1     165      64            81           174           401   
2   54    0     172      95           138           163           386   
3   55    0     175      94           100           202           380   
4   75    0     190      80            88           181           360   
5   13    0     169      51           100           167           321   
6   40    1     160      52            77           129           377   
7   49    1     162      54            78             0           376   
8   44    0     168      56            84           118           354   
9   50    1     167      67            89           130           383   

   t_interval  p_interval  qrs  ...   KY    KZ   LA   LB  LC   LD   LE    LF  \
0         174         121  -16  ...  0.0   9.0 -0.9  0.0   0  0.9  2.9  23.3   
1         149          39   25  ...  0.0   8.5  0.0  0.0   0  0.2  2.1  20.4   
2         185         102   96  ...  0.0   9.5 -2.4  0.0   0  0.3  3.4  12.3   
3         179         143   28  ...  0.0  12.2 -2.2  0.0   0  0.4  2.6  34.6   
4         177         103  -16  ...  0.0  13.1 -3.6  0.0   0 -0.1  3.9  25.4   
5         174          91  107  ... -0.6  12.2 -2.8  0.0   0  0.9  2.2  13.5   
6         133          77   77  ...  0.0   6.5  0.0  0.0   0  0.4  1.0  14.3   
7         157          70   67  ...  0.0   8.2 -1.9  0.0   0  0.1  0.5  15.8   
8         160          63   61  ...  0.0   7.0 -1.3  0.0   0  0.6  2.1  12.5   
9         156          73   85  ... -0.6  10.8 -1.7  0.0   0  0.8  0.9  20.1   

     LG  diagnosis  
0  49.4          8  
1  38.8          6  
2  49.0         10  
3  61.6          1  
4  62.8          7  
5  31.1         14  
6  20.5          1  
7  19.8          1  
8  30.9          1  
9  25.1         10  

[10 rows x 280 columns]

In [4]:
type(data)

pandas.core.frame.DataFrame

In [5]:
data["diagnosis"].unique()

array([ 8,  6, 10,  1,  7, 14,  3, 16,  2,  4,  5,  9, 15], dtype=int64)

In [6]:
data["diagnosis"].value_counts()

1     735
10    150
2     132
6      75
16     66
3      45
4      45
5      39
9      27
15     15
14     12
7       9
8       6
Name: diagnosis, dtype: int64

In [7]:
data["diagnosis"].value_counts()

1     735
10    150
2     132
6      75
16     66
3      45
4      45
5      39
9      27
15     15
14     12
7       9
8       6
Name: diagnosis, dtype: int64

In [8]:
data["Sex"].value_counts()

1    747
0    609
Name: Sex, dtype: int64

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1356 entries, 0 to 1355
Columns: 280 entries, Age to diagnosis
dtypes: float64(121), int64(159)
memory usage: 2.9 MB


In [10]:
data.describe()

Age          Sex       Height       Weight  qrs_duration  \
count  1356.000000  1356.000000  1356.000000  1356.000000   1356.000000   
mean     46.471239     0.550885   166.188053    68.170354     88.920354   
std      16.454474     0.497587    37.142898    16.578554     15.353051   
min       0.000000     0.000000   105.000000     6.000000     55.000000   
25%      36.000000     0.000000   160.000000    59.000000     80.000000   
50%      47.000000     1.000000   164.000000    68.000000     86.000000   
75%      58.000000     1.000000   170.000000    79.000000     94.000000   
max      83.000000     1.000000   780.000000   176.000000    188.000000   

       p-r_interval  q-t_interval   t_interval   p_interval          qrs  ...  \
count   1356.000000   1356.000000  1356.000000  1356.000000  1356.000000  ...   
mean     155.152655    367.207965   169.949115    90.004425    33.676991  ...   
std       44.809176     33.360774    35.606765    25.807576    45.397893  ...   
min        0.000000    232.000000   108.000000     0.000000  -172.000000  ...   
25%      142.000000    350.000000   148.000000    79.000000     3.750000  ...   
50%      157.000000    367.000000   162.000000    91.000000    40.000000  ...   
75%      175.000000    384.000000   179.000000   102.000000    66.000000  ...   
max      524.000000    509.000000   381.000000   205.000000   169.000000  ...   

                KY           KZ           LA           LB      LC  \
count  1356.000000  1356.000000  1356.000000  1356.000000  1356.0   
mean     -0.278982     9.048009    -1.457301     0.003982     0.0   
std       0.548471     3.470298     2.000951     0.050081     0.0   
min      -4.100000     0.000000   -28.600000     0.000000     0.0   
25%      -0.425000     6.600000    -2.100000     0.000000     0.0   
50%       0.000000     8.800000    -1.100000     0.000000     0.0   
75%       0.000000    11.200000     0.000000     0.000000     0.0   
max       0.000000    23.600000     0.000000     0.800000     0.0   

                LD           LE           LF           LG    diagnosis  
count  1356.000000  1356.000000  1356.000000  1356.000000  1356.000000  
mean      0.514823     1.222345    19.326106    29.473230     3.880531  
std       0.347274     1.424999    13.493952    18.480273     4.403843  
min      -0.800000    -6.000000   -44.200000   -38.600000     1.000000  
25%       0.400000     0.500000    11.450000    17.550000     1.000000  
50%       0.500000     1.350000    18.100000    27.900000     1.000000  
75%       0.700000     2.100000    25.825000    41.125000     6.000000  
max       2.400000     6.000000    88.800000   115.900000    16.000000  

[8 rows x 280 columns]

In [11]:
data = data.fillna(data.mean())

In [12]:
data.isnull()

Age    Sex  Height  Weight  qrs_duration  p-r_interval  q-t_interval  \
0     False  False   False   False         False         False         False   
1     False  False   False   False         False         False         False   
2     False  False   False   False         False         False         False   
3     False  False   False   False         False         False         False   
4     False  False   False   False         False         False         False   
...     ...    ...     ...     ...           ...           ...           ...   
1351  False  False   False   False         False         False         False   
1352  False  False   False   False         False         False         False   
1353  False  False   False   False         False         False         False   
1354  False  False   False   False         False         False         False   
1355  False  False   False   False         False         False         False   

      t_interval  p_interval    qrs  ...     KY     KZ     LA     LB     LC  \
0          False       False  False  ...  False  False  False  False  False   
1          False       False  False  ...  False  False  False  False  False   
2          False       False  False  ...  False  False  False  False  False   
3          False       False  False  ...  False  False  False  False  False   
4          False       False  False  ...  False  False  False  False  False   
...          ...         ...    ...  ...    ...    ...    ...    ...    ...   
1351       False       False  False  ...  False  False  False  False  False   
1352       False       False  False  ...  False  False  False  False  False   
1353       False       False  False  ...  False  False  False  False  False   
1354       False       False  False  ...  False  False  False  False  False   
1355       False       False  False  ...  False  False  False  False  False   

         LD     LE     LF     LG  diagnosis  
0     False  False  False  False      False  
1     False  False  False  False      False  
2     False  False  False  False      False  
3     False  False  False  False      False  
4     False  False  False  False      False  
...     ...    ...    ...    ...        ...  
1351  False  False  False  False      False  
1352  False  False  False  False      False  
1353  False  False  False  False      False  
1354  False  False  False  False      False  
1355  False  False  False  False      False  

[1356 rows x 280 columns]

In [13]:
X = data.iloc[:,:-1]
#create feature matrix
#reader=csv.reader(open("feature.csv","r"),delimiter=",")
#X=list(reader)
X=numpy.array(X)
X=X.astype(numpy.float)

y = data.iloc[:,-1]
#create result vector
#reader=csv.reader(open("target_output.csv","r"),delimiter=",")
#y=list(reader)
y=numpy.array(y)
y=y.astype(numpy.int)


C:\Users\Romes\anaconda3\envs\csv1\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
C:\Users\Romes\anaconda3\envs\csv1\lib\site-packages\ipykernel_launcher.py:13: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.

In [17]:
#applying random forests to get pricipal attributes
from sklearn.ensemble import ExtraTreesClassifier # scikit-learn we get algorithm features
model = ExtraTreesClassifier()
model.fit(X, y.ravel())  # fit means training


numpy.savetxt("randforrests.csv", model.feature_importances_, fmt='%s', delimiter=",")

#selecting features 
c=0;
important_features=numpy.zeros((278),dtype=numpy.float)
important_features_index=numpy.zeros((278),dtype=numpy.int)

for i in range (0,278):
    if((model.feature_importances_[i]*1000)>=4.5):
        important_features[c]=model.feature_importances_[i]
        important_features_index[c]=i
        c=c+1

print(important_features)
print(important_features_index)
print("The no of features =",c)

#features are reduced  from 278

numpy.savetxt("import_features_index_after_random_forrests.csv",important_features_index, fmt='%s', delimiter=",")

#new matrix compirising of reduced features
newX=numpy.zeros((1356 ,c),dtype=numpy.float)
for i in range (0,1356 ):
    for j in range (0,c):
        newX[i][j]=X[i][important_features_index[j]]


print(newX)

numpy.savetxt("reduced_features.csv",newX, fmt='%s', delimiter=",")

C:\Users\Romes\anaconda3\envs\csv1\lib\site-packages\ipykernel_launcher.py:11: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Romes\anaconda3\envs\csv1\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more detai

[0.0048762  0.00582981 0.00463607 0.00880365 0.00496433 0.00653901
 0.00719977 0.00526717 0.00834332 0.00464194 0.00545549 0.02109933
 0.00629831 0.00577721 0.0057431  0.00521096 0.00587469 0.00455458
 0.00469364 0.00583833 0.00460681 0.00505502 0.00926963 0.00473828
 0.00558386 0.00629904 0.02591608 0.01966369 0.00452907 0.00771126
 0.00520982 0.00710269 0.01341656 0.00777874 0.01224369 0.01057747
 0.00834004 0.00647603 0.00463067 0.00585654 0.0047356  0.00546517
 0.00624972 0.00481908 0.00560574 0.00465473 0.0050699  0.00524901
 0.00483523 0.00483803 0.01074322 0.0065193  0.00601408 0.00705118
 0.00458868 0.00494358 0.00832026 0.00524129 0.00649342 0.00484998
 0.00583094 0.00461271 0.00600745 0.00582383 0.01095785 0.00777915
 0.00575361 0.00573353 0.00474339 0.00841831 0.00456076 0.0050868
 0.00614804 0.00622173 0.0055637  0.0141705  0.00575111 0.00553111
 0.00870298 0.00526792 0.00627134 0.0083305  0.00487091 0.00705678
 0.00588546 0.00476429 0.00695404 0.00598409 0.00463527 0.00677

C:\Users\Romes\anaconda3\envs\csv1\lib\site-packages\ipykernel_launcher.py:29: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


[[ 75.    0.   80.  ...  62.9  -0.3   2.9]
 [ 56.    1.   64.  ...  43.4  -0.5   2.1]
 [ 54.    0.   95.  ...  48.2   0.9   3.4]
 ...
 [ 36.    0.   68.  ... -63.6   1.2   1. ]
 [ 32.    1.   55.  ...  61.    0.2   2.4]
 [ 78.    1.   70.  ...  38.9  -0.3   1.6]]


In [15]:
print(model.feature_importances_)

[5.17982552e-03 6.02507177e-03 4.54149004e-03 4.99519334e-03
 8.99343112e-03 5.14386526e-03 8.00238076e-03 7.09112590e-03
 6.24304328e-03 4.42287137e-03 8.71666704e-03 4.10550262e-03
 5.22504125e-03 4.97258452e-03 1.99300375e-02 2.90182898e-03
 4.98226835e-03 5.63217926e-03 7.61036038e-04 0.00000000e+00
 5.42684503e-03 8.35787457e-05 0.00000000e+00 4.05974997e-04
 1.16709640e-03 5.22059558e-05 9.80896670e-05 4.30433662e-03
 5.12554833e-03 5.16876295e-03 1.07337125e-03 4.14379391e-05
 5.17123718e-03 6.17236819e-04 2.92339884e-03 2.98782219e-04
 9.47652869e-05 5.33563141e-05 5.44551054e-04 5.55796893e-03
 4.10796592e-03 3.46377936e-03 1.42765823e-03 7.09764700e-05
 4.00031907e-03 0.00000000e+00 1.60495968e-03 0.00000000e+00
 6.73470177e-04 1.19475391e-04 3.11998798e-04 4.86088714e-03
 6.35854577e-03 2.26618645e-03 1.17525768e-03 0.00000000e+00
 4.90507431e-03 1.32884883e-04 1.43399601e-04 1.09883892e-04
 1.26478484e-03 2.82418439e-04 3.04674683e-04 2.49673036e-03
 5.02938824e-03 4.360286

In [ ]:
x = pd.read_csv('reduced_features.csv')

In [ ]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(x,y[:-1],test_size=0.2,random_state=100)

# KNN Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
clf_KNN = KNeighborsClassifier(n_neighbors=13)

clf_KNN.fit(X_train,y_train)

In [ ]:
y_pred_knn  = clf_KNN.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred_knn,y_test))
score_knn = accuracy_score(y_pred_knn,y_test)